# Introduction

In [2]:
import numpy as np

In [3]:
arr = np.array([-1, 2, 0, 5], dtype=np.int32)
arr

array([-1,  2,  0,  5])

In [4]:
print(repr(arr))
print(arr)
print(str(arr))

array([-1,  2,  0,  5])
[-1  2  0  5]
[-1  2  0  5]
