# Mathematics

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [4]:
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [5]:
arr - 0.1

array([[0.9, 1.9],
       [2.9, 3.9]])

In [7]:
arr ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [8]:
import math

In [9]:
math.sqrt(9)

3.0

In [10]:
arr2 = np.array([
    [1, 4],
    [9, 16]
])

In [12]:
(arr2 ** 0.5).astype(int)

array([[1, 2],
       [3, 4]])

In [13]:
math.sqrt(arr2)

TypeError: only size-1 arrays can be converted to Python scalars

In [15]:
sqrt = np.vectorize(math.sqrt)
sqrt(arr2)

array([[1., 2.],
       [3., 4.]])

In [17]:
np.exp2(np.array([
    [0, 1],
    [2, 3]
]))

array([[1., 2.],
       [4., 8.]])

In [18]:
np.array([
    [1, 2],
    [3, 4]
]) ** np.array([
    [9, 0],
    [2, 0.5]
])

array([[1., 1.],
       [9., 2.]])

In [19]:
mat1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
mat2 = np.array([
    [-1, 0, 1],
    [3, 2, -4]
])
mat2

array([[-1,  0,  1],
       [ 3,  2, -4]])

In [21]:
np.matmul(mat1, mat2)

array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])

In [22]:
np.pi

3.141592653589793

In [23]:
np.e

2.718281828459045