# Random

In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
np.random.randint(5) # 0 - 4

3

In [4]:
np.random.randint(5, high=7) # 5 or 6

5

In [5]:
np.random.seed(1)
np.random.randint(5)

3

In [6]:
vec = np.array([1, 2, 3, 4, 5])

In [13]:
np.random.shuffle(vec)
vec

array([1, 5, 3, 2, 4])

In [14]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.random.shuffle(arr) # Only shuffles the first dimension (here, row)
arr

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [22]:
# Uniform Distribution
np.random.uniform() # 0-1

0.7159705159683643

In [39]:
np.random.uniform(low=-2, high=3)

0.06269420751513044

In [54]:
np.random.uniform(size=10)

array([0.76424161, 0.2127337 , 0.07425843, 0.09541925, 0.16220551,
       0.35646368, 0.09530781, 0.14326301, 0.93101293, 0.57658422])

In [92]:
np.random.uniform(low=-0.5, high=0.5, size=(2, 2)).round(2)

array([[-0.11, -0.42],
       [-0.15, -0.5 ]])

In [128]:
# Normal (Gaussian) Distribution
np.random.normal()

0.4056633076405743

In [148]:
np.random.normal(loc=10, scale=5, size=(3, 2))

array([[11.99300773,  3.20722686],
       [20.29718599,  4.53993251],
       [ 6.41818624,  8.33849937]])

In [150]:
people = np.array([
    'Manu',
    'Henry',
    'Santosh',
    'Lata'
])
people

array(['Manu', 'Henry', 'Santosh', 'Lata'], dtype='<U7')

In [156]:
np.random.choice(people)

'Manu'

In [157]:
np.random.choice(people, size=3)

array(['Santosh', 'Henry', 'Santosh'], dtype='<U7')

In [163]:
np.random.choice(people, size=(3, 2))

array([['Lata', 'Lata'],
       ['Santosh', 'Lata'],
       ['Lata', 'Henry']], dtype='<U7')

In [171]:
np.random.choice(people, size=(3, 4), p=[0.1, 0.1, 0.1, 0.7])

array([['Lata', 'Lata', 'Santosh', 'Lata'],
       ['Lata', 'Lata', 'Lata', 'Santosh'],
       ['Lata', 'Lata', 'Lata', 'Lata']], dtype='<U7')