# Indexing

In [2]:
import numpy as np

In [10]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1[0], arr1[4]

(1, 5)

In [7]:
arr = np.array([
    [6, 3],
    [0, 2]
])
arr

array([[6, 3],
       [0, 2]])

In [8]:
arr[0]

array([6, 3])

In [9]:
arr[:, 0]

array([6, 0])

In [12]:
arr1[2:4]

array([3, 4])

In [14]:
arr1[:]

array([1, 2, 3, 4, 5])

In [15]:
arr1[:-1]

array([1, 2, 3, 4])

In [17]:
arr3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr3[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr3[0].argmax()

2

In [30]:
np.argmin(arr3)

0

In [33]:
arr4 = np.array([
    [-2, -1, -3],
    [ 4,  5,  6],
    [-3,  9,  1]
])
arr4

array([[-2, -1, -3],
       [ 4,  5,  6],
       [-3,  9,  1]])

In [37]:
arr4.argmin(axis=0)

array([2, 0, 0], dtype=int64)

In [49]:
arr5 = np.array([
    [
        [1, -2],
        [-5, 8]
    ],
    [
        [9, 0],
        [-6, 7]
    ]
])
arr5

array([[[ 1, -2],
        [-5,  8]],

       [[ 9,  0],
        [-6,  7]]])

In [55]:
arr5.shape

(2, 2, 2)

In [62]:
arr5.argmax(axis=0)

array([[1, 1],
       [0, 0]], dtype=int64)

In [63]:
np.unravel_index(arr5.argmax(), arr5.shape)

(1, 0, 0)

In [64]:
arr5[1, 0, 0]

9