# Filtering

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [0, 2, 3],
    [1, 3, -6],
    [-3, -2, -1]
])
arr

array([[ 0,  2,  3],
       [ 1,  3, -6],
       [-3, -2, -1]])

In [3]:
arr == 0

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [4]:
arr > 2

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [5]:
arr != 1

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [6]:
~(arr != 1)

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [7]:
arr2 = np.array([
    [0, 2, np.nan],
    [1, np.nan, -6],
    [np.nan, -2, 1]
])
arr2

array([[ 0.,  2., nan],
       [ 1., nan, -6.],
       [nan, -2.,  1.]])

In [8]:
np.random.shuffle(arr2)
arr2

array([[ 1., nan, -6.],
       [nan, -2.,  1.],
       [ 0.,  2., nan]])

In [9]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
type(arr) is float and np.isnan(arr)

False

In [15]:
vec = np.array([0, 3, 5, 3, 1])
vec

array([0, 3, 5, 3, 1])

In [16]:
np.where(vec == 3)

(array([1, 3], dtype=int64),)

In [30]:
# Greater than 1
gt_1 = np.where(arr > 1)

In [21]:
x, y = gt_1

In [29]:
np.array([
    x, y
]).transpose((1, 0))

array([[0, 1],
       [0, 2],
       [1, 1]], dtype=int64)

In [34]:
vec

array([0, 3, 5, 3, 1])

In [35]:
np.where(
    vec >= 3,
    1, # True value
    0 # False value
)

array([0, 1, 1, 1, 0])

In [36]:
arr

array([[ 0,  2,  3],
       [ 1,  3, -6],
       [-3, -2, -1]])

In [38]:
np.where(
    arr <= 0,
    np.array([
        [1e1, 1e2, 1e3],
        [1e4, 1e5, 1e6],
        [1e7, 1e8, 1e9]
    ]) - 1,
    -1
).astype(int)

array([[        9,        -1,        -1],
       [       -1,        -1,    999999],
       [  9999999,  99999999, 999999999]])

In [39]:
arr2 = np.array([
    [-2, -1, -3, 0],
    [4, 5, -6, 62],
    [3, 9, 1, -45]
])
arr2

array([[ -2,  -1,  -3,   0],
       [  4,   5,  -6,  62],
       [  3,   9,   1, -45]])

In [40]:
arr2 > 0

array([[False, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [41]:
np.any(arr2 > 0)

True

In [45]:
np.all(arr2 > 0)

False

In [49]:
arr2

array([[ -2,  -1,  -3,   0],
       [  4,   5,  -6,  62],
       [  3,   9,   1, -45]])

In [50]:
np.any(arr2 == 0, axis=0)

array([False, False, False,  True])

In [53]:
rarr = np.random.randint(3, 20, size=(4, 2, 3))
rarr

array([[[14, 10, 16],
        [17, 12,  5]],

       [[ 4, 18,  7],
        [ 7, 14, 10]],

       [[ 7, 12, 19],
        [ 7, 16,  6]],

       [[ 8,  3, 15],
        [ 8,  9, 14]]])

In [57]:
np.any(rarr == 3, axis=0)

array([[False,  True, False],
       [False, False, False]])

In [58]:
np.any(rarr == 3, axis=1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])