# Statistics

In [1]:
import numpy as np

In [3]:
arr = np.array([
    [0, 72, 3],
    [1, 3, -60],
    [-3, -2, 4]
])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [5]:
arr.max(), arr.min()

(72, -60)

In [6]:
arr.max(axis=0)

array([ 1, 72,  4])

In [7]:
all(arr.min(axis=1) == arr.min(axis=-1))

True

In [8]:
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [9]:
arr.mean()

2.0

In [10]:
arr.mean(axis=0)

array([ -0.66666667,  24.33333333, -17.66666667])

In [11]:
from fractions import Fraction

In [13]:
(arr + Fraction()).mean(axis=0)

array([Fraction(-2, 3), Fraction(73, 3), Fraction(-53, 3)], dtype=object)

In [18]:
np.median(arr)

1.0

In [20]:
np.median(arr, axis=1)

array([ 3.,  1., -2.])

In [21]:
arr.var()

977.3333333333334

In [28]:
arr.var(axis=0) # Population variance

array([   2.88888889, 1140.22222222,  896.22222222])

In [29]:
arr.var(axis=0, ddof=1) # Sample variance

array([   4.33333333, 1710.33333333, 1344.33333333])

In [35]:
arr.std() # ddof = 0, ddof -> Delta Degrees of Freedom

31.262330900515614