# Aggregation 

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [  0,  72,   3],
    [  1,   3, -60],
    [ -3,  -2,   4]
])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [3]:
arr.sum()

18

In [4]:
arr.sum(axis=0)

array([ -2,  73, -53])

In [5]:
arr.cumsum()

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18], dtype=int32)

In [6]:
arr.cumsum(axis=1)

array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]], dtype=int32)

In [8]:
rra = np.array([
    [-15,   6,   1],
    [  8,   9,  -4],
    [  5, -21,  18]
])
arr, rra

(array([[  0,  72,   3],
        [  1,   3, -60],
        [ -3,  -2,   4]]),
 array([[-15,   6,   1],
        [  8,   9,  -4],
        [  5, -21,  18]]))

In [11]:
np.concatenate([arr, rra] # , axis=0
              )

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])

In [12]:
np.concatenate([arr, rra], axis=1)

array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])